services.bound:
  gateway: service-1

service-1.gateway:
  zookeeper.uri: localhost
  pub.topic: messages

gateway:
  zookeeper.uri: ${${services.bound.gateway}.gateway.zookeeper.uri}
  pub.topic: ${${services.bound.gateway}.gateway.pub.topic}

consumer.group: ${random.uuid}